In [27]:
import pickle
import numpy as np
import folium

In [2]:
data = pickle.load(open('./pickles/realtor_clean.p','rb'))
residual_model = pickle.load(open('./pickles/final_model.p','rb'))
location_model = pickle.load(open('./pickles/location_model.p','rb'))

In [6]:
data[(data['BsmtQual_Ex'] == 1) & (data['ExterQual_Ex'] == 1)]

GrLivArea  LotArea  OverallQual  OverallCond  TotalBsmtSF  \
710       1203.0  12003.0            5            4       1176.0   
959       2977.0  25500.0            4            6       2491.0   
2879      2494.0  12073.0            7            5       1362.0   
3419      1712.0   7218.0            4            3        840.0   
4290      1824.0  13500.0            6            8          0.0   
5242      2899.0  25502.0            7            5       1475.0   
5873      1068.0   8260.0            5            6        588.0   
6493      1368.0  12850.0            7            7       1252.0   
7112      1553.0  16050.0            7            5       1553.0   
7974       849.0  10800.0            6            5        849.0   
8322      2170.0   3834.0            6            7        861.0   
11353     2132.0  12085.0            5            5       2132.0   
11817     1739.0  10104.0            6            5        828.0   
12239     2025.0  11613.0            5            5       1074.0   
14102     1656.0   6931.0            5            7        746.0   
14383     1664.0   9740.0            6            6       1718.0   
14408      845.0  12025.0            4            5        845.0   
19391     1776.0   9697.0            3            7        823.0   
20753      970.0  10370.0            7            5        912.0   

       BedroomAbvGr  TotRmsAbvGrd  Fireplaces  PoolArea   latitude  ...  \
710             3.0           6.0         1.0       0.0  42.056932  ...   
959             4.0          10.0         0.0       0.0  42.059253  ...   
2879            3.0           8.0         1.0       0.0  42.053440  ...   
3419            3.0          10.0         1.0       0.0  42.052273  ...   
4290            4.0          10.0         2.0       0.0  42.035114  ...   
5242            4.0           8.0         1.0       0.0  42.037190  ...   
5873            2.0           5.0         0.0       0.0  42.043729  ...   
6493            3.0           6.0         1.0       0.0  42.048842  ...   
7112            2.0           6.0         0.0       0.0  42.034853  ...   
7974            1.0           4.0         0.0       0.0  42.033633  ...   
8322            5.0          10.0         0.0       0.0  42.027791  ...   
11353           3.0           8.0         1.0       0.0  42.028360  ...   
11817           3.0           7.0         0.0       0.0  42.017939  ...   
12239           3.0           9.0         0.0       0.0  42.017837  ...   
14102           3.0           7.0         1.0       0.0  42.019007  ...   
14383           3.0           9.0         1.0       0.0  42.018169  ...   
14408           3.0           5.0         0.0       0.0  42.019545  ...   
19391           3.0           9.0         1.0       0.0  41.994208  ...   
20753           3.0           6.0         0.0       0.0  41.986498  ...   

       KitchenQual_Fa  KitchenQual_Gd  KitchenQual_Po  KitchenQual_TA  \
710                 0               0               0               1   
959                 0               0               0               1   
2879                1               0               0               0   
3419                0               0               0               1   
4290                0               0               0               1   
5242                0               0               0               1   
5873                0               0               0               1   
6493                0               0               0               1   
7112                0               1               0               0   
7974                0               1               0               0   
8322                0               1               0               0   
11353               0               0               0               1   
11817               0               0               0               1   
12239               0               0               0               1   
14102               1               0             

In [55]:
test_old = data.drop(['Residuals'], axis = 1).iloc[np.random.randint(data.shape[0]),:].to_frame().transpose()

In [71]:
test_new = test_old.copy()

In [69]:
location_model.predict(test_old[['latitude','e_long']]) + residual_model.predict(test_old.drop(['e_long','Location_Price','latitude','longitude'],axis = 1))

array([133795.17518706])

In [73]:
location_model.predict(test_old[['latitude','e_long']]) + residual_model.predict(test_new.drop(['e_long','Location_Price','latitude','longitude'],axis = 1))

array([255502.11463543])

In [76]:
test_new.drop(['e_long','latitude','longitude'],axis = 1)[test_new != 0].dropna(axis = 1).transpose()

15825
GrLivArea              864.0
LotArea               8212.0
OverallQual              6.0
OverallCond              5.0
TotalBsmtSF            864.0
BedroomAbvGr             2.0
TotRmsAbvGrd             5.0
LandSlope_Gtl            1.0
BldgType_1Fam            1.0
HouseStyle_1Story        1.0
RoofMatl_WdShngl         1.0
Exterior1st_Stucco       1.0
ExterQual_Ex             1.0
Foundation_BrkTil        1.0
BsmtQual_Ex              1.0
Heating_GasA             1.0
CentralAir_Y             1.0
KitchenQual_TA           1.0
Quarter_Q3               1.0
Location_Price      104380.0

In [72]:
test_new['Quarter_Q2'] = 0; test_new['Quarter_Q3'] = 1
test_new['BsmtQual_Gd'] = 0; test_new['BsmtQual_Ex'] = 1
test_new['Age'] = 0
test_new['RoofMatl_CompShg'] = 0; test_new['RoofMatl_WdShngl'] = 1
test_new['ExterQual_TA'] = 0; test_new['ExterQual_Ex'] = 1
test_new['CentralAir_N'] = 0; test_new['CentralAir_Y'] = 1
residual_model.predict(test_new.drop(['latitude','longitude'],axis = 1)) - residual_model.predict(test_old.drop(['latitude','longitude'],axis = 1))

In [78]:
data.shape[0]

8901

In [95]:
row = data.iloc[0,:]
row.loc[[col for col in row.index if 'ExterQual' in col]] =  0

<ipython-input-95-0a5fb16e5a17>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row.loc[[col for col in row.index if 'ExterQual' in col]] =  0


In [104]:
residual_model.predict(row.drop(['Location_Price','longitude','latitude','e_long','Residuals']).to_frame().transpose())

array([76366.43796615])

In [109]:
def potential(row):
    new_row = row.copy()
    new_row.Age = 0
    new_row.Quarter_Q2 = 0; new_row.Quarter_Q3 = 1
    #ExterQual
    new_row.loc[[col for col in new_row.index if 'ExterQual' in col]] =  0
    new_row.ExterQual_Ex = 1
    #Kitchenn
    new_row.loc[[col for col in new_row.index if 'Kitchen' in col]] =  0
    new_row.KitchenQual_Ex = 1
    #Bsmt
    new_row.loc[[col for col in new_row.index if 'BsmtQual' in col]] =  0
    new_row.BsmtQual_Ex = 1
    #Central_Air
    new_row.CentralAir_N = 0
    new_row.CentralAir_Y = 1
    #Roof
    new_row.loc[[col for col in new_row.index if 'Roof' in col]] =  0
    new_row.RoofMatl_WdShngl = 1
    #model
    potential_ = residual_model.predict(new_row.drop(['Location_Price','longitude','latitude','e_long','Residuals']).to_frame().transpose()) - residual_model.predict(row.drop(['Location_Price','longitude','latitude','e_long','Residuals']).to_frame().transpose())
    return(potential_)

In [113]:
data_w_potential = data.copy()
data_w_potential['potential'] = data.apply(potential,axis = 1)
data_w_potential.loc[:,'potential'] = data_w_potential.loc[:,'potential'].apply(lambda x: x[0])

In [128]:
data_most_potential = data_w_potential.sort_values(by = 'potential')[-20:]

In [130]:
sum(data_most_potential.potential)

2751033.4469959675

In [129]:
m = folium.Map(location=[test_old.latitude,test_old.longitude],tiles='Stamen Toner')
for i in range(0,data_most_potential.shape[0]):
    folium.Marker(location = [data_most_potential.latitude.iloc[i], data_most_potential.longitude.iloc[i]]).add_to(m)
m

In [77]:
m = folium.Map(location=[test_old.latitude,test_old.longitude],tiles='Stamen Toner')
folium.Marker([test_old.latitude,test_old.longitude],popup = 'Example House').add_to(m)
m